name: Cache
description: Tarball, Rsync & S3 Cache Kit for Buildkite. Supports Linux and macOS. (Windows is on the way)
author: https://github.com/gencer
requirements:
  - aws
  - tar
configuration:
  properties:
    key:
      type: string
    backend:
      type: string
      required: false
    s3:
      profile:
        type: string
      bucket:
        type: string
    tarball:
      max:
        type: number
    paths:
      type: [string, array]
    env:
      type: [string, array]
      minimum: 2
  additionalProperties: false
