name: Cache
description: Restore and Save directories using a cache key with tarballs, Rsync and S3
author: https://github.com/gencer
requirements:
  - aws
  - tar
configuration:
  properties:
    rsync_storage:
      type: string
    tarball_storage:
      type: string
    tarball_keep_max_days:
      type: number
    cache_key:
      type: string
    paths:
      type: [ string, array ]
    env:
      type: [ string, array ]
      minimum: 2
  additionalProperties: false
